/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdbc.sample;

import java.sql.Connection;
import java.sql.DriverManager;

public class App {
	
	// set documentation on timeout settings at https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15
	// loginTimeout and socketTimeout are in milliseconds whereas queryTimeout is in seconds
	static String url = "jdbc:sqlserver://localhost;databaseName=ride_tracker_db;loginTimeout=30;socketTimeout=500;queryTimeout=5";
	

    public static void main(String[] args) throws Exception {
    	
		RideTracker rt = new RideTracker();
		long start = System.currentTimeMillis();
		try (Connection conn = DriverManager.getConnection(url, "sa", "Brespo%85")) {
	    	for (int i = 0 ; i < 200; i ++) {
	        	rt.batchUpdate(conn, i);
	        	Thread.sleep(2300);
	    	}
		} finally {
	    	long end = System.currentTimeMillis();
	    	long elapsed = end - start;
	    	System.out.println(elapsed + "seconds");
		}

    }
    
}
